name: CI/CD Julliuz Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rodar testes
        run: |
          pytest || true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy (exemplo)
        run: |
          echo "Aqui você pode adicionar comandos de deploy via FTP, SSH, rsync, etc."
          # Exemplo para Hostinger (ajuste conforme necessário)
          # lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} -e "mirror -R ./ /public_html/julliuz-bot; quit" ${{ secrets.FTP_HOST }} 