name: CI + Deploy Bot Telegram

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: [5432:5432]
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis:7
        ports: [6379:6379]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Roda os testes
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          REDIS_URL: redis://localhost:6379/0
          PYTHONPATH: .
        run: pytest tests/
        

      - name: Deploy no servidor via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/julliuz-bot
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart julliuz-bot
